// <auto-generated />
using System;
using AddressBook.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AddressBook.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180828172706_InitalCreate")]
    partial class InitalCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("AddressBook.API.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsBookmarked");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("AddressBook.API.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ContactId");

                    b.Property<string>("EmailAddress");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Email");
                });

            modelBuilder.Entity("AddressBook.API.Models.Number", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ContactId");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Number");
                });

            modelBuilder.Entity("AddressBook.API.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ContactId");

                    b.Property<string>("TagName");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("AddressBook.API.Models.Email", b =>
                {
                    b.HasOne("AddressBook.API.Models.Contact")
                        .WithMany("EmailList")
                        .HasForeignKey("ContactId");
                });

            modelBuilder.Entity("AddressBook.API.Models.Number", b =>
                {
                    b.HasOne("AddressBook.API.Models.Contact")
                        .WithMany("NumberList")
                        .HasForeignKey("ContactId");
                });

            modelBuilder.Entity("AddressBook.API.Models.Tag", b =>
                {
                    b.HasOne("AddressBook.API.Models.Contact")
                        .WithMany("TagList")
                        .HasForeignKey("ContactId");
                });
#pragma warning restore 612, 618
        }
    }
}
